### ISSUE TITLE
Sidenav切换页面无法保存前页面数据

### ISSUE THREAD

**Issue by FadeRainbow** [Konyaco/compose-fluent-ui#25]
![image](https://github.com/Konyaco/compose-fluent-ui/assets/110913615/0592b5ae-828a-4d91-bb82-35ccb8aedaea)
![image](https://github.com/Konyaco/compose-fluent-ui/assets/110913615/cc99e177-b4ab-4e18-9356-0899b44825ee)
![image](https://github.com/Konyaco/compose-fluent-ui/assets/110913615/4b7fb9e0-6c34-41eb-aa74-6ecbd4d3868b)
求解决方法

**Comment by FadeRainbow** [comment]
他的SettingScreen写在Sidenav里，当我改变switcher时lightColors没有转变成darkColors

**Comment by Konyaco** [comment]
> 他的SettingScreen写在Sidenav里，当我改变switcher时lightColors没有转变成darkColors

你在 `App(ViewModel())` 里又创建了个新实例。。。

**Comment by FadeRainbow** [comment]
> > 他的SettingScreen写在Sidenav里，当我改变switcher时lightColors没有转变成darkColors
> 
> 你在 里又创建了个新实例。。。`App(ViewModel())`

已解决谢谢
