### ISSUE TITLE
AwtFontManager Not Found

### ISSUE THREAD

**Issue by sky130** [Konyaco/compose-fluent-ui#26]
In the latest version of skiko, [AwtFontManager was be remove](https://github.com/JetBrains/skiko/pull/835).
Because of that, it isnt possible to use fluent-ui now.
How to fix it? 😢 
![image](https://github.com/Konyaco/compose-fluent-ui/assets/64515462/a4d064bd-13bc-40b1-bf36-2c6a22c176fa)
@Konyaco

**Comment by Konyaco** [comment]
Fonts will be removed since the latest version uses Segoe as default. Check dev branch?

**Comment by CH4019** [comment]
AwtFontManager cannot be found. 
The current solution is to manually set the initial value of defaultFontFamily to skip this part.
![2024-02-17 210931](https://github.com/Konyaco/compose-fluent-ui/assets/77958033/9e31efb0-54cc-4010-b6b1-8a5c28659a15)
![ 2024-02-17 211013](https://github.com/Konyaco/compose-fluent-ui/assets/77958033/19e57b18-2783-4108-8eba-646c28a0236d)

**Comment by sky130** [comment]
> AwtFontManager cannot be found. The current solution is to manually set the initial value of defaultFontFamily to skip this part. ![2024-02-17 210931](https://private-user-images.githubusercontent.com/77958033/305645526-9e31efb0-54cc-4010-b6b1-8a5c28659a15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzY0MTQsIm5iZiI6MTcwODE3NjExNCwicGF0aCI6Ii83Nzk1ODAzMy8zMDU2NDU1MjYtOWUzMWVmYjAtNTRjYy00MDEwLWI2YjEtOGE1YzI4NjU5YTE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDEzMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxY2VlYjJmNzhmZjFhMjUxNmFjZmFiYzVjODc5NzZhNTc4OTFjZmU1NDcxNGQyZDViYWU2YmExYWEzMTdlYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mjH1lTp0AHnsKdTmuwOPYV7wDi5QBFL5KlQGlV5mo5s) ![ 2024-02-17 211013](https://private-user-images.githubusercontent.com/77958033/305645546-19e57b18-2783-4108-8eba-646c28a0236d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxNzY0MTQsIm5iZiI6MTcwODE3NjExNCwicGF0aCI6Ii83Nzk1ODAzMy8zMDU2NDU1NDYtMTllNTdiMTgtMjc4My00MTA4LThlYmEtNjQ2YzI4YTAyMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDEzMjE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4YjE5MGYxNTQwODc4ZDkxZjcyODRlNzliMjA5Y2Y0ZDk4NDYwOTFmOTAxNzc0MTMyMjU5ZjVmN2Q0ODU5MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iGCKDUZNUAqGAC7Sg7SRO4IjJ8JJaLHg5XoSzmnSomo)

well
