### ISSUE TITLE
[Prototype] expose outsideBorder parameter in Buttons.

### ISSUE THREAD

**Issue by Sanlorng** [Konyaco/compose-fluent-ui#38]
See [XAML Border API](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.border.backgroundsizing?view=winrt-22621#windows-ui-xaml-controls-border-backgroundsizing)

**Comment by Konyaco** [comment]
See `layer-compare` branch.

![image](https://github.com/Konyaco/compose-fluent-ui/assets/17498623/435d41f7-61e9-453c-b315-39787cb4edc3)

In the previous `layer` implementation. If we set `outsideBorder` to `false`, Layer will use content's size. If set to `true`, the `Layer` will expand by the size of paddings. Generally, the first one should be the correct behavior. I had seen that problem previously, but I haven't solved it instantly.

A:
This parameter only affects on `background` in `Layer`, we don't add padding to the content. So we will get the same effect as `Box`. That is the most convenient implementation.

B:
If the content has `maxConstraints`, we propagate the `constraints - padding`, so the `32.dp` in `Box(Modifier.size(32.dp))` will contain padding. If the content does not have `maxConstraints`, we just measure and put it.

I haven't tried Plan B yet. Maybe there are some undetectable problems.

The correct implementation of `SplitButton` should use a different border on four sides, which is not supported by compose.

**Comment by Sanlorng** [comment]
Maybe we can provide a basic api `Modifier.fluentBorder` and `FluentBorderStroke`，that can provide a BackgroundSizing configuration .

**Comment by Konyaco** [comment]
> Maybe we can provide a basic api `Modifier.fluentBorder` and `FluentBorderStroke`，that can provide a BackgroundSizing configuration .

I think there's no need to do that. If we add more tricky codes, it could potentially lead to more issues when the compose API changes.

**Comment by Sanlorng** [comment]
> > Maybe we can provide a basic api `Modifier.fluentBorder` and `FluentBorderStroke`，that can provide a BackgroundSizing configuration .
> 
> I think there's no need to do that. If we add more tricky codes, it could potentially lead to more issues when the compose API changes.
I found a better way to implement background padding.
```Kotlin
@Composable
private fun Modifier.newLayer(shape: Shape = FluentRoundedCornerShape(4.dp), backgroundSizing: BackgroundSizing = BackgroundSizing.OuterBorderEdge): Modifier {
    val paddingShape = remember {
        object : Shape {
            override fun createOutline(size: Size, layoutDirection: LayoutDirection, density: Density): Outline {
                return when {
                    shape is FluentRoundedCornerShape && backgroundSizing == BackgroundSizing.OuterBorderEdge -> {
                        with(density) {
                            val padding = 1.dp.toPx()
                            val innerSize = Size(size.width - 2*padding, size.height - 2* padding)
                            when(val oldOutline = shape.createOutline(innerSize, layoutDirection, density)) {
                                is Outline.Rectangle -> {
                                    Outline.Rectangle(oldOutline.rect.translate(Offset(padding, padding)))
                                }
                                is Outline.Rounded -> {
                                    Outline.Rounded(oldOutline.roundRect.translate(Offset(padding, padding)))
                                }
                                is Outline.Generic -> {
                                    Outline.Generic(oldOutline.path.apply {
                                        translate(Offset(padding, padding))
                                    })
                                }
                            }
                        }
                    }
                    else -> shape.createOutline(size, layoutDirection, density)
                }
            }
        }
    }
    return then(Modifier.border(1.dp, FluentTheme.colors.stroke.control.default, shape = shape)
        .background(FluentTheme.colors.fillAccent.default, shape = paddingShape)
    )
}
```
```Kotlin
        NewLayer {
            Box(Modifier.size(32.dp))
        }

        NewLayer(backgroundSizing = BackgroundSizing.InnerBorderEdge) {
            Box(Modifier.size(32.dp))
        }
```
##### Screenshot
![image](https://github.com/Konyaco/compose-fluent-ui/assets/26089739/1080a6d2-ab1a-4f20-b863-f7571de849c4)

**Comment by Sanlorng** [comment]
> See `layer-compare` branch.
> 
> ![image](https://private-user-images.githubusercontent.com/17498623/319031177-435d41f7-61e9-453c-b315-39787cb4edc3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTc2MTUsIm5iZiI6MTcxMjU1NzMxNSwicGF0aCI6Ii8xNzQ5ODYyMy8zMTkwMzExNzctNDM1ZDQxZjctNjFlOS00NTNjLWIzMTUtMzk3ODdjYjRlZGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2MjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMmJhYTBiMWM4MzdjMjViMGM1Njk0MzlmMzJjMmYyZDQ3YWFlMWI4ZGIwOWQ1ZTdmZWFlNDY3NWE0YTRmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xNtSFnVefU0tx91sB2lonG2wLt8E9jVAVxHiOqHVjoQ)
> 
> In the previous `layer` implementation. If we set `outsideBorder` to `false`, Layer will use content's size. If set to `true`, the `Layer` will expand by the size of paddings. Generally, the first one should be the correct behavior. I had seen that problem previously, but I haven't solved it instantly.
> 
> A: This parameter only affects on `background` in `Layer`, we don't add padding to the content. So we will get the same effect as `Box`. That is the most convenient implementation.
> 
> B: If the content has `maxConstraints`, we propagate the `constraints - padding`, so the `32.dp` in `Box(Modifier.size(32.dp))` will contain padding. If the content does not have `maxConstraints`, we just measure and put it.
> 
> I haven't tried Plan B yet. Maybe there are some undetectable problems.
> 
> The correct implementation of `SplitButton` should use a different border on four sides, which is not supported by compose.

new layer implementation, see [`layer-compare-2`](https://github.com/Konyaco/compose-fluent-ui/tree/layer-compare-2) branch
![image](https://github.com/Konyaco/compose-fluent-ui/assets/26089739/5906bd90-c7ef-42b1-b9db-db2c35247238)

**Comment by Konyaco** [comment]
Looks well! We can use this method.

**Comment by Konyaco** [comment]
> Looks well! We can use this method.

So we can remove the `FluentCornerShape` also?

**Comment by Sanlorng** [comment]
> > Looks well! We can use this method.
> 
> So we can remove the `FluentCornerShape` also?

Yes

**Comment by Sanlorng** [comment]
> > Looks well! We can use this method.
> 
> So we can remove the `FluentCornerShape` also?

See Commit [[fluent] Deprecate `FluentRoundedCorner` and `FluentCornerSize`](https://github.com/Konyaco/compose-fluent-ui/pull/37/commits/932378ae3e34fb99bfab6a0baabd02652f2cb37d)
#37
