### ISSUE TITLE
New gallery icon for android target.

### ISSUE THREAD

**Issue by Sanlorng** [Konyaco/compose-fluent-ui#43]
The android target used a sample android icon. could you update the android target icon? @123Duo3 
Action:  
1. right click `androidMain` source set.
2. click `New` action
3. click `Image Asset` action
4. choose the new icon.
![image](https://github.com/Konyaco/compose-fluent-ui/assets/26089739/0ff36def-3785-4a81-b39b-58cde26ff5eb)
![image](https://github.com/Konyaco/compose-fluent-ui/assets/26089739/0bc365d4-1b80-4cb7-935f-dd3a23a1a92b)

**Comment by 123Duo3** [comment]
Updated in 3c6e31d1d0313d2d072100cfb08d2d89010da447 .
With launcher icon and monochome icon.
![Launcher Icon](https://github.com/Konyaco/compose-fluent-ui/assets/12569997/d401834b-e91f-4dd7-9221-a10f15dff6f6)
![Monochome Icon](https://github.com/Konyaco/compose-fluent-ui/assets/12569997/da93b369-ed08-4dc8-ae45-70401bb30355)
