### ISSUE TITLE
DropDownButton示例应用中的问题

### ISSUE THREAD

**Issue by LiuPack** [Konyaco/compose-fluent-ui#67]
<img width="304" alt="image" src="https://github.com/Konyaco/compose-fluent-ui/assets/153405759/44d91c76-3623-4dad-9d25-b3aac6cda7bc">
初次点击展开背景是正常的，再次重复点击按钮，会导致背景变成透明

**Comment by Sanlorng** [comment]
Android上吗？

**Comment by LiuPack** [comment]
> Android上吗？如果是Android上的话，请尝试切换到`components/acrylic_update`分支再跑一下，看看还会不会有这个问题

我是在 Mac Desktop 上运行的

**Comment by Sanlorng** [comment]
> > Android上吗？如果是Android上的话，请尝试切换到`components/acrylic_update`分支再跑一下，看看还会不会有这个问题
> 
> 我是在 Mac Desktop 上运行的

你也可以尝试用这个分支试一下，看看有没有解决你的问题，我隐约记得有几个bug，更新到haze 0.7.2就好了，但是我现在在我机器上试不出来

**Comment by LiuPack** [comment]
> > > Android上吗？如果是Android上的话，请尝试切换到`components/acrylic_update`分支再跑一下，看看还会不会有这个问题
> > 
> > 
> > 我是在 Mac Desktop 上运行的
> 
> 你也可以尝试用这个分支试一下，看看有没有解决你的问题，我隐约记得有几个bug，更新到haze 0.7.2就好了，但是我现在在我机器上试不出来

ok，components/acrylic_update 分支的没问题

**Comment by Sanlorng** [comment]
> > > > Android上吗？如果是Android上的话，请尝试切换到`components/acrylic_update`分支再跑一下，看看还会不会有这个问题
> > > 
> > > 
> > > 我是在 Mac Desktop 上运行的
> > 
> > 你也可以尝试用这个分支试一下，看看有没有解决你的问题，我隐约记得有几个bug，更新到haze 0.7.2就好了，但是我现在在我机器上试不出来
> 
> ok，components/acrylic_update 分支的没问题

Snapshot 版本应该没这问题了
