### ISSUE TITLE
After clicking the dropdownbutton multiple times, a transparent background will appear

### ISSUE THREAD

**Issue by crowforkotlin** [Konyaco/compose-fluent-ui#79]
After clicking the dropdownbutton multiple times, a transparent background will appear
![image](https://github.com/user-attachments/assets/c7df724b-c414-4024-9d5c-7db95a810176)

**Comment by Sanlorng** [comment]
> After clicking the dropdownbutton multiple times, a transparent background will appear ![image](https://private-user-images.githubusercontent.com/60876546/384307401-c7df724b-c414-4024-9d5c-7db95a810176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNzA1MDYsIm5iZiI6MTczMTA3MDIwNiwicGF0aCI6Ii82MDg3NjU0Ni8zODQzMDc0MDEtYzdkZjcyNGItYzQxNC00MDI0LTlkNWMtN2RiOTVhODEwMTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDEyNTAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMzkxYmEyNzU4ZGZmMzZiZGMzMmUyNmFmNmJiZjQ1MGI1NmE5ZjkwNGZkYTgwMjI2NjdkMjAzMmFlYjEyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FdpPg3XpcwkHOYRPovk3W1g3dPSE8QxKFIA8qvJ0UQM)

Try to use the snapshot version, [Gallery application artifact](https://github.com/Konyaco/compose-fluent-ui/actions/runs/11727419736), that will be fixed, duplicated with #67
