### ISSUE TITLE
Issue: Could not resolve dependency com.konyaco:fluent:0.0.1-dev.8

### ISSUE THREAD

**Issue by Jparrgam** [Konyaco/compose-fluent-ui#89]
I am encountering an issue when trying to resolve the fluent dependency in my Kotlin Multiplatform project. The dependency fails to resolve during the build process.

My Configuration

Here is the relevant section of my build.gradle.kts:

``` kotlin 
commonMain.dependencies {
    // Fluent theme
    implementation("com.konyaco:fluent:0.0.1-dev.8")
    implementation("com.konyaco:fluent-icons-extended:0.0.1-dev.8")
}
```

Steps to Reproduce

	1.	Add the dependencies listed above to the commonMain.dependencies block in a Kotlin Multiplatform project.
	2.	Attempt to sync the Gradle project or build it.

Observed Behavior

The build fails with the following error:

`Could not resolve com.konyaco:fluent:0.0.1-dev.8.`

**Comment by Sanlorng** [comment]
> I am encountering an issue when trying to resolve the fluent dependency in my Kotlin Multiplatform project. The dependency fails to resolve during the build process.
> 
> My Configuration
> 
> Here is the relevant section of my build.gradle.kts:
> 
> ```kotlin
> commonMain.dependencies {
>     // Fluent theme
>     implementation("com.konyaco:fluent:0.0.1-dev.8")
>     implementation("com.konyaco:fluent-icons-extended:0.0.1-dev.8")
> }
> ```
> 
> Steps to Reproduce
> 
> ```
> 1.	Add the dependencies listed above to the commonMain.dependencies block in a Kotlin Multiplatform project.
> 2.	Attempt to sync the Gradle project or build it.
> ```
> 
> Observed Behavior
> 
> The build fails with the following error:
> 
> `Could not resolve com.konyaco:fluent:0.0.1-dev.8.`

First, please ensure that you have added Maven Central to your dependencies repositories. Secondly, make sure that your project only includes JVM and Android targets. Dev 8 only supports JVM and Android targets.

**Comment by Jparrgam** [comment]
> > I am encountering an issue when trying to resolve the fluent dependency in my Kotlin Multiplatform project. The dependency fails to resolve during the build process.
> > My Configuration
> > Here is the relevant section of my build.gradle.kts:
> > ```kotlin
> > commonMain.dependencies {
> >     // Fluent theme
> >     implementation("com.konyaco:fluent:0.0.1-dev.8")
> >     implementation("com.konyaco:fluent-icons-extended:0.0.1-dev.8")
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Steps to Reproduce
> > ```
> > 1.	Add the dependencies listed above to the commonMain.dependencies block in a Kotlin Multiplatform project.
> > 2.	Attempt to sync the Gradle project or build it.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Observed Behavior
> > The build fails with the following error:
> > `Could not resolve com.konyaco:fluent:0.0.1-dev.8.`
> 
> First, please ensure that you have added Maven Central to your dependencies repositories. Secondly, make sure that your project only includes JVM and Android targets. Dev 8 only supports JVM and Android targets.

in my Gradle configuration, I have mavenCentral(). I’ll share it with you:

``` kotlin
pluginManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri("https://aws.oss.sonatype.org/content/repositories/snapshots/")
        }
    }
}

dependencyResolutionManagement {
    repositories {
        google {
            mavenContent {
                includeGroupAndSubgroups("androidx")
                includeGroupAndSubgroups("com.android")
                includeGroupAndSubgroups("com.google")
            }
        }
        mavenCentral()
        maven {
            url = uri("https://aws.oss.sonatype.org/content/repositories/snapshots/")
        }
    }
}
```
@Sanlorng Which version supports Wasm?

**Comment by Sanlorng** [comment]
> > > I am encountering an issue when trying to resolve the fluent dependency in my Kotlin Multiplatform project. The dependency fails to resolve during the build process.
> > > My Configuration
> > > Here is the relevant section of my build.gradle.kts:
> > > ```kotlin
> > > commonMain.dependencies {
> > >     // Fluent theme
> > >     implementation("com.konyaco:fluent:0.0.1-dev.8")
> > >     implementation("com.konyaco:fluent-icons-extended:0.0.1-dev.8")
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Steps to Reproduce
> > > ```
> > > 1.	Add the dependencies listed above to the commonMain.dependencies block in a Kotlin Multiplatform project.
> > > 2.	Attempt to sync the Gradle project or build it.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Observed Behavior
> > > The build fails with the following error:
> > > `Could not resolve com.konyaco:fluent:0.0.1-dev.8.`
> > 
> > 
> > First, please ensure that you have added Maven Central to your dependencies repositories. Secondly, make sure that your project only includes JVM and Android targets. Dev 8 only supports JVM and Android targets.
> 
> in my Gradle configuration, I have mavenCentral(). I’ll share it with you:
> 
> ```kotlin
> pluginManagement {
>     repositories {
>         google {
>             mavenContent {
>                 includeGroupAndSubgroups("androidx")
>                 includeGroupAndSubgroups("com.android")
>                 includeGroupAndSubgroups("com.google")
>             }
>         }
>         mavenCentral()
>         gradlePluginPortal()
>         maven {
>             url = uri("https://aws.oss.sonatype.org/content/repositories/snapshots/")
>         }
>     }
> }
> 
> dependencyResolutionManagement {
>     repositories {
>         google {
>             mavenContent {
>                 includeGroupAndSubgroups("androidx")
>                 includeGroupAndSubgroups("com.android")
>                 includeGroupAndSubgroups("com.google")
>             }
>         }
>         mavenCentral()
>         maven {
>             url = uri("https://aws.oss.sonatype.org/content/repositories/snapshots/")
>         }
>     }
> }
> ```
> 
> @Sanlorng Which version supports Wasm?

1. Add snapshot repository (https://s01.oss.sonatype.org/content/repositories/snapshots/) to your dependenciesRepositories
2. Set the library to `0.1.0-SNAPSHOT` version.
