### ISSUE TITLE
CompositionLocal LocalFontFamilyResolver not present 问题

### ISSUE THREAD

**Issue by CH4019** [Konyaco/compose-fluent-ui#94]
## 问题描述

当使用 [compose-custom-window-frame](https://github.com/amir1376/compose-custom-window-frame) 与 FluentTheme 一起配合来实现自定义窗口样式时，出现这个问题

## 环境说明
jdk：Jetbrains Runtime 17.0.12
kotlin.version ：2.1.0
compose.version：1.8.0-alpha01

## 问题截图

![image](https://github.com/user-attachments/assets/cbb45fe6-37fe-423d-b199-ebd57653e4e2)
![image](https://github.com/user-attachments/assets/f4029868-d527-4dc7-b2f8-201682bfab96)

**Comment by Sanlorng** [comment]
我不确定LocalFontFamilyRsolver在1.8.0是否有变动，建议你试试1.7.1，看看会不会有同样的问题

**Comment by Sanlorng** [comment]
我在本地试了一下，建议你在Window内部再调用这个FluentTheme，因为application 域内并没有初始化这个变量，你在application域直接使用BasicText也会有同样的问题

**Comment by Sanlorng** [comment]
如果你需要在Window域外使用主题函数，建议使用FluentThemeConfiguration这个函数，需要注意的一点：在FluentTheme的外部使用这个函数时，一定要手动设置contentDialogHostState不然也会遇到类似的报错。

**Comment by CH4019** [comment]
> 我在本地试了一下，建议你在Window内部再调用这个FluentTheme，因为application 域内并没有初始化这个变量，你在application域直接使用BasicText也会有同样的问题

但是使用MaterialTheme来测试是没有该问题的，是否可以参考MaterialTheme来优化这个情况

**Comment by Sanlorng** [comment]
> > 我在本地试了一下，建议你在Window内部再调用这个FluentTheme，因为application 域内并没有初始化这个变量，你在application域直接使用BasicText也会有同样的问题
> 
> 但是使用MaterialTheme来测试是没有该问题的，是否可以参考MaterialTheme来优化这个情况

优化不了，因为需要配置FontIcon来实现Windows 11上的图标体验，如果真有需要在DesktopWindow外引用的需要，就用FluentThemeConfiguration，这个就没有设置FontIcon，所以不会报错。
